name: Publish packages

on:
  push:
    tags:
    - 'v**'

  workflow_dispatch:

jobs:
  publish_binary_packages:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        name: [ubuntu22, ubuntu20, el8, suse15]

        include:
          - name: ubuntu22
            asset_suffix: ubuntu22.04_amd64.deb
            build_files: deb/jammy
            asset_prefix: '_'
            asset_path: flex
            sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
            python_version: "3.8"                
          - name: ubuntu20
            asset_suffix: ubuntu20.04_amd64.deb
            build_files: deb/focal
            asset_prefix: '_'
            asset_path: flex
            sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
            python_version: "3.8"
          - name: el8
            asset_suffix: el8.x86_64.rpm
            build_files: rpm/el8
            asset_prefix: '-'
            asset_path: flex/rpmbuild/RPMS/x86_64
            sign_cmd: rpm --addsign
            python_version: "3.6"
          - name: suse15
            asset_suffix: suse15.x86_64.rpm
            build_files: rpm/suse15
            asset_prefix: '-'
            asset_path: flex/rpmbuild/RPMS/x86_64
            sign_cmd: rpm --addsign
            python_version: "3.6"            

    steps:
    - name: Getting build dependencies
      id: get_dependencies
      run: |      
         git clone -b flex https://github.com/GluuFederation/packaging
         mkdir -p flex/flex-src/opt/
         cp -rp packaging/${{ matrix.build_files }}/* flex/
         curl https://raw.githubusercontent.com/GluuFederation/flex/main/flex-linux-setup/flex_linux_setup/flex_setup.py > flex/flex_setup.py
         sudo add-apt-repository ppa:deadsnakes/ppa
         sudo apt-get update
         sudo apt-get install -y python${{ matrix.python_version }}
         sudo apt install -y build-essential devscripts debhelper rpm dpkg-sig python3-ldap3 python3-requests python3-ruamel.yaml python3-pymysql python3-crypto python${{ matrix.python_version }}-distutils python3-prompt-toolkit python3-psycopg2
         sudo cp -r /usr/lib/python3/dist-packages /usr/lib/python${{ matrix.python_version }}/
         sudo python${{ matrix.python_version }} -m pip install psycopg2-binary
    - name: Running install and build
      id: run_build
      run: |
         cd flex/
         sudo python${{ matrix.python_version }} flex_setup.py -download-exit 
         cp -r /opt/dist flex-src/opt/
         cp -r /opt/jans flex-src/opt/
         touch flex-src/opt/jans/jans-setup/package
         rm -rf install.py install jans-cli
         rm -rf flex-src/opt/jans/jans-setup/logs/setup.log
         rm -rf flex-src/opt/jans/jans-setup/logs/setup_error.log         
         sed -i "s/%VERSION%/1.0.3/g" run-build.sh
         cat run-build.sh
         sudo ./run-build.sh
    - name: "Set asset name env"
      run: |
        if [ "${{ matrix.name }}" == "ubuntu20" ] || [ "${{ matrix.name }}" == "ubuntu22" ]; then
          echo "ASSET_PRESUFFIX=~" >> $GITHUB_ENV  
        elif echo "1.0.3" | grep "-"; then
          echo "ASSET_PRESUFFIX=." >> $GITHUB_ENV
        else
          echo "ASSET_PRESUFFIX=-" >> $GITHUB_ENV
        fi         
    - name: Upload binaries to release
      id: upload_binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}1.0.3${{ env.ASSET_PRESUFFIX }}${{ matrix.asset_suffix }}
        asset_name: flex${{ matrix.asset_prefix }}1.0.3${{ env.ASSET_PRESUFFIX }}${{ matrix.asset_suffix }}
        tag: 1.0.3
  
       






